# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '画板' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 画板
  pod "KRProgressHUD"
end
