# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '联网状态检测' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 联网状态检测
  pod 'ReachabilitySwift'
end
