# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '音乐' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 音乐
  pod 'MJExtension'
end
